"""
Company entity - Represents a company in the multi-tenant system
"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Company:
    """
    Company entity

    Attributes:
        name: Company name
        cnpj: Brazilian company registration number (optional)
        phone: Company phone number (optional)
        plan: Subscription plan (basic, premium, enterprise)
        is_active: Whether the company is active
        users_count: Number of users in this company
        id: Company UUID (generated by backend)
        created_at: When the company was created
        updated_at: When the company was last updated
    """
    name: str
    cnpj: Optional[str] = None
    phone: Optional[str] = None
    plan: str = "basic"
    is_active: bool = True
    users_count: int = 0
    id: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    def to_dict(self):
        """Convert to dictionary for API requests"""
        data = {
            "name": self.name,
            "plan": self.plan,
        }
        if self.cnpj:
            data["cnpj"] = self.cnpj
        if self.phone:
            data["phone"] = self.phone
        return data

    @staticmethod
    def from_dict(data: dict) -> 'Company':
        """Create Company from dictionary"""
        return Company(
            id=data.get("id"),
            name=data["name"],
            cnpj=data.get("cnpj"),
            phone=data.get("phone"),
            plan=data.get("plan", "basic"),
            is_active=data.get("is_active", True),
            users_count=data.get("users_count", 0),
            created_at=datetime.fromisoformat(data["created_at"].replace("Z", "+00:00")) if data.get("created_at") else None,
            updated_at=datetime.fromisoformat(data["updated_at"].replace("Z", "+00:00")) if data.get("updated_at") else None,
        )
