"""
User entity - Represents a user in the system
"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, List


@dataclass
class User:
    """
    User entity

    Attributes:
        email: User email (unique identifier)
        name: User full name
        company_id: Company UUID this user belongs to
        is_active: Whether the user is active
        is_super_admin: Whether the user is a super admin
        role_ids: List of role IDs assigned to the user
        features: List of feature permissions
        id: User UUID (generated by backend)
        created_at: When the user was created
        updated_at: When the user was last updated
    """
    email: str
    name: str
    company_id: str
    is_active: bool = True
    is_super_admin: bool = False
    role_ids: List[str] = None
    features: List[str] = None
    id: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    def __post_init__(self):
        """Initialize default values"""
        if self.role_ids is None:
            self.role_ids = []
        if self.features is None:
            self.features = []

    def has_feature(self, feature: str) -> bool:
        """Check if user has a specific feature permission"""
        if self.is_super_admin:
            return True
        return feature in self.features

    def is_admin(self) -> bool:
        """Check if user is super admin or has admin role"""
        if self.is_super_admin:
            return True
        # Verifica se tem as features de admin (users.create é uma feature exclusiva de admin)
        return "users.create" in self.features

    def to_dict(self):
        """Convert to dictionary for API requests"""
        return {
            "email": self.email,
            "name": self.name,
            "company_id": self.company_id,
            "is_active": self.is_active,
            "is_super_admin": self.is_super_admin,
            "role_ids": self.role_ids,
        }

    @staticmethod
    def from_dict(data: dict) -> 'User':
        """Create User from dictionary"""
        return User(
            id=data.get("id"),
            email=data["email"],
            name=data["name"],
            company_id=data["company_id"],
            is_active=data.get("is_active", True),
            is_super_admin=data.get("is_super_admin", False),
            role_ids=data.get("role_ids", []) or [],
            features=data.get("features", []) or [],
            created_at=datetime.fromisoformat(data["created_at"].replace("Z", "+00:00")) if data.get("created_at") else None,
            updated_at=datetime.fromisoformat(data["updated_at"].replace("Z", "+00:00")) if data.get("updated_at") else None,
        )
